/**
 * Gift Guides Data
 * Curated gift guides with items and categories
 */

import { GiftGuide, GuideCategory, GuideItem } from './types';

// ============================================================================
// CATEGORIES
// ============================================================================

export const categories: GuideCategory[] = [
  { slug: 'gift-guides', label: 'Gift Guides', icon: '🎁', description: 'Curated gift collections for every occasion' },
  { slug: 'trends', label: 'Trends', icon: '🔥', description: 'Trending gifts and hot items everyone wants' },
  { slug: 'tech', label: 'Tech', icon: '💻', description: 'Gadgets and electronics for tech enthusiasts' },
  { slug: 'baby-kid', label: 'Baby & Kid', icon: '🧸', description: 'Perfect presents for little ones' },
  { slug: 'travel', label: 'Travel', icon: '🧳', description: 'Essentials for travelers and adventurers' },
  { slug: 'style', label: 'Style', icon: '👗', description: 'Fashion and accessories for the style-conscious' },
  { slug: 'best-sellers', label: 'Best Sellers', icon: '⭐️', description: 'Most popular and highly rated gifts' },
  { slug: 'kitchen', label: 'Kitchen', icon: '🍳', description: 'Culinary tools and kitchen essentials' },
  { slug: 'beauty', label: 'Beauty', icon: '💄', description: 'Beauty products and self-care items' },
  { slug: 'home', label: 'Home', icon: '🏡', description: 'Home decor and living essentials' },
  { slug: 'wellness', label: 'Wellness', icon: '🧘‍♀️', description: 'Health, fitness, and wellness products' },
];

// ============================================================================
// HERO GUIDE
// ============================================================================

export const heroGuide: GiftGuide = {
  slug: 'secret-santa-gifts-for-coworkers-2025',
  categoryTag: 'SECRET SANTA GIFTS',
  title: '10 Secret Santa Gift Ideas Your Coworkers Will Actually Love 2025',
  description:
    'Struggling to find the perfect Secret Santa gift that your coworkers will actually appreciate. This guide is packed with unique and thoughtful ideas that go beyond the typical generic presents.',
  heroImageAlt:
    'Selection of Secret Santa gifts including earbuds, a smart speaker, a leather item and thermal mugs on a pastel abstract background',
  heroImagePath: '/gift-guides/secret-santa-coworkers-hero.jpg',
  categories: ['gift-guides', 'trends'],
};

// ============================================================================
// SIDEBAR GUIDES
// ============================================================================

export const sidebarGuides: GiftGuide[] = [
  {
    slug: 'christmas-gifts-for-her-2025',
    categoryTag: 'CHRISTMAS GIFTS FOR HER',
    title: '50 Best Christmas Gifts for Her 2025',
    description:
      'Finding the perfect Christmas gift for her can feel overwhelming. This guide brings together fifty ideas that cover beauty, style and cozy at home gifts.',
    heroImageAlt:
      'Beauty products, a handbag and small presents grouped on a warm pastel background',
    heroImagePath: '/gift-guides/christmas-gifts-for-her-2025.jpg',
    categories: ['gift-guides', 'style', 'beauty'],
  },
  {
    slug: 'stocking-stuffers-under-50-2025',
    categoryTag: 'STOCKING STUFFERS',
    title: '25 Best Stocking Stuffers Under 50 for 2025',
    description:
      'Stuff stockings without emptying your wallet. This list features twenty five small presents under fifty that still feel special.',
    heroImageAlt:
      'Assorted small gifts like a mug, notebook and gadgets arranged on a colorful gradient background',
    heroImagePath: '/gift-guides/stocking-stuffers-under-50-2025.jpg',
    categories: ['gift-guides', 'best-sellers'],
  },
  {
    slug: 'anniversary-gifts-for-her-2025',
    categoryTag: 'ANNIVERSARY GIFTS FOR HER',
    title: '15 Thoughtful Anniversary Gifts for Her in 2025',
    description:
      'Celebrate your relationship with thoughtful presents picked to match different tastes and milestones.',
    heroImageAlt:
      'Jewelry and small keepsakes set on a soft pastel surface',
    heroImagePath: '/gift-guides/anniversary-gifts-for-her-2025.jpg',
    categories: ['gift-guides', 'style'],
  },
  {
    slug: 'thanksgiving-kitchen-gadgets-2025',
    categoryTag: 'THANKSGIVING KITCHEN GADGETS',
    title:
      'Thanksgiving Dinner Essentials The Best Kitchen Gadgets of 2025',
    description:
      'Elevate your Thanksgiving feast with kitchen tools that save time and stress, from smart thermometers to upgraded pans.',
    heroImageAlt:
      'Modern kitchen gadgets such as blender, coffee gear and utensils on a warm background',
    heroImagePath: '/gift-guides/thanksgiving-kitchen-gadgets-2025.jpg',
    categories: ['kitchen', 'home'],
  },
];

// ============================================================================
// ALL GUIDES (for easy access)
// ============================================================================

export const allGuides: GiftGuide[] = [heroGuide, ...sidebarGuides];

// ============================================================================
// GUIDE ITEMS
// ============================================================================

export const guideItems: Record<string, GuideItem[]> = {
  'secret-santa-gifts-for-coworkers-2025': [
    {
      id: 'ss-1',
      title: 'JLab Go Air Pop+ Wireless Earbuds',
      description: 'Compact wireless earbuds with 35+ hours of playback. Perfect for the music-loving coworker who commutes.',
      image: 'https://m.media-amazon.com/images/I/61fGS5b7eNL._AC_SL1500_.jpg',
      price: 17.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CZ4PWQPD?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'ss-2',
      title: 'Rocketbook Everlast Reusable Notebook',
      description: 'Eco-friendly reusable notebook with cloud sync. Write, scan, erase, and repeat. Perfect for note-takers.',
      image: 'https://m.media-amazon.com/images/I/71LrvFz0JbL._AC_SL1500_.jpg',
      price: 29.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B071Y3MSRK?tag=romkow-20',
      category: 'Office',
    },
    {
      id: 'ss-3',
      title: 'Heated Mouse Pad with Wrist Rest',
      description: 'Ergonomic mouse pad that keeps hands warm during cold office days. USB-powered with adjustable heat.',
      image: 'https://m.media-amazon.com/images/I/71zXxH0xqnL._AC_SL1500_.jpg',
      price: 19.95,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BJ3QKFYQ?tag=romkow-20',
      category: 'Office',
    },
    {
      id: 'ss-4',
      title: 'Milk Frother Handheld',
      description: 'Electric milk frother with 3 whisk heads for creating café-quality foam. Coffee lovers will appreciate this.',
      image: 'https://m.media-amazon.com/images/I/61ypPVT-S7L._AC_SL1500_.jpg',
      price: 16.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CHN63XFS?tag=romkow-20',
      category: 'Kitchen',
    },
    {
      id: 'ss-5',
      title: 'Desktop Retro Arcade Game',
      description: 'Mini Pac-Man arcade game for the desk. Classic gameplay with authentic sound effects.',
      image: 'https://m.media-amazon.com/images/I/71gSXOGbhqL._AC_SL1500_.jpg',
      price: 19.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07GQ2JKK4?tag=romkow-20',
      category: 'Fun',
    },
    {
      id: 'ss-6',
      title: 'Insulated Water Bottle with Time Markers',
      description: 'Motivational water bottle with hourly reminders to stay hydrated. Keeps drinks cold for 24 hours.',
      image: 'https://m.media-amazon.com/images/I/61qGa8rz8YL._AC_SL1500_.jpg',
      price: 24.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CLP9YYXP?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'ss-7',
      title: 'LED Desk Lamp with Wireless Charging',
      description: 'Modern desk lamp with adjustable brightness and built-in wireless charging pad for phones.',
      image: 'https://m.media-amazon.com/images/I/61b7d3VqfYL._AC_SL1500_.jpg',
      price: 29.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B5V1QX7N?tag=romkow-20',
      category: 'Office',
    },
    {
      id: 'ss-8',
      title: 'Shower Steamers Aromatherapy Set',
      description: 'Pack of 6 shower steamers in relaxing scents. Turn any shower into a spa experience.',
      image: 'https://m.media-amazon.com/images/I/81L1f0BSOJL._AC_SL1500_.jpg',
      price: 14.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B08JCM9KGS?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'ss-9',
      title: 'Gourmet Hot Sauce Gift Set',
      description: 'Collection of artisan hot sauces including truffle-infused varieties. Perfect for foodies.',
      image: 'https://m.media-amazon.com/images/I/81xKzpWOBVL._AC_SL1500_.jpg',
      price: 24.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07KRHBR7W?tag=romkow-20',
      category: 'Food',
    },
    {
      id: 'ss-10',
      title: 'Cozy Sherpa Throw Blanket',
      description: 'Ultra-soft leopard print throw blanket perfect for chilly office days. Machine washable.',
      image: 'https://m.media-amazon.com/images/I/91KdLq8gHEL._AC_SL1500_.jpg',
      price: 27.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BXQYG74Y?tag=romkow-20',
      category: 'Home',
    },
  ],

  'christmas-gifts-for-her-2025': [
    {
      id: 'xmas-1',
      title: 'UGG Classic Mini Platform Boots',
      description: 'Iconic UGG boots with a modern platform sole. Available in multiple colors, perfect for cozy winter days.',
      image: 'https://m.media-amazon.com/images/I/71JYZBXvwXL._AC_SL1500_.jpg',
      price: 159.95,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B09PQLY9YB?tag=romkow-20',
      category: 'Fashion',
    },
    {
      id: 'xmas-2',
      title: 'Dyson Airwrap Multi-Styler Complete',
      description: 'The ultimate hair styling tool with 6 attachments. Curls, waves, smooths, and dries with no heat damage.',
      image: 'https://m.media-amazon.com/images/I/61tMPU7oYKL._AC_SL1500_.jpg',
      price: 599.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CLSTQ1KN?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'xmas-3',
      title: 'Charlotte Tilbury Pillow Talk Beauty Set',
      description: 'Luxury makeup set featuring the iconic Pillow Talk lipstick, liner, and blush in a beautiful gift box.',
      image: 'https://m.media-amazon.com/images/I/71pO3nRNbkL._AC_SL1500_.jpg',
      price: 89.00,
      currency: 'USD',
      url: 'https://www.charlottetilbury.com/us/product/pillow-talk-beauty-icons',
      category: 'Beauty',
    },
    {
      id: 'xmas-4',
      title: 'Owala FreeSip Insulated Water Bottle',
      description: 'Viral water bottle with dual-drinking modes in vibrant colors. Keeps drinks cold for 24 hours.',
      image: 'https://m.media-amazon.com/images/I/71YOgPl0aBL._AC_SL1500_.jpg',
      price: 27.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B7XGY5Q7?tag=romkow-20',
      category: 'Lifestyle',
    },
    {
      id: 'xmas-5',
      title: 'KitchenAid Artisan Stand Mixer',
      description: 'Classic stand mixer in 45+ colors. Perfect for holiday baking and everyday cooking.',
      image: 'https://m.media-amazon.com/images/I/81FDXdXe0BL._AC_SL1500_.jpg',
      price: 449.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BXBL6XHT?tag=romkow-20',
      category: 'Kitchen',
    },
    {
      id: 'xmas-6',
      title: 'LANEIGE Lip Sleeping Mask',
      description: 'Viral overnight lip treatment that deeply hydrates and smooths. Available in berry and vanilla scents.',
      image: 'https://m.media-amazon.com/images/I/61f49xkVZTL._AC_SL1500_.jpg',
      price: 24.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CKTNB5SP?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'xmas-7',
      title: 'Bose QuietComfort Headphones',
      description: 'Premium noise-cancelling headphones with exceptional sound quality. Perfect for travel and focus.',
      image: 'https://m.media-amazon.com/images/I/51S3N+YoqIL._AC_SL1200_.jpg',
      price: 349.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CCZ26B5V?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'xmas-8',
      title: 'Madewell Transport Tote Bag',
      description: 'Classic leather tote in soft mahogany suede. Timeless design perfect for work and weekends.',
      image: 'https://m.media-amazon.com/images/I/81ZqO9C9aTL._AC_SL1500_.jpg',
      price: 158.00,
      currency: 'USD',
      url: 'https://www.madewell.com/transport-tote-bag',
      category: 'Fashion',
    },
    {
      id: 'xmas-9',
      title: 'Candle Warmer Lamp',
      description: 'Elegant lamp-style candle warmer that melts candles without flame. Safe for renters and pet owners.',
      image: 'https://m.media-amazon.com/images/I/61RP6FKlsAL._AC_SL1500_.jpg',
      price: 39.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CN5HRT49?tag=romkow-20',
      category: 'Home',
    },
    {
      id: 'xmas-10',
      title: 'Kodak Dock Plus Photo Printer',
      description: 'Instant photo printer that connects to phones. Print memories on the spot with stunning quality.',
      image: 'https://m.media-amazon.com/images/I/71qmjV7sOTL._AC_SL1500_.jpg',
      price: 119.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07V2GH9Z5?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'xmas-11',
      title: 'Barefoot Dreams CozyChic Cardigan',
      description: 'Incredibly soft and cozy cardigan that feels like a warm hug. Perfect for lounging.',
      image: 'https://m.media-amazon.com/images/I/71RqYx2aVtL._AC_SL1500_.jpg',
      price: 147.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BK4LDTR9?tag=romkow-20',
      category: 'Fashion',
    },
    {
      id: 'xmas-12',
      title: 'Popcorn Maker Machine',
      description: 'Retro-style popcorn maker for movie nights at home. Makes healthy, oil-free popcorn in minutes.',
      image: 'https://m.media-amazon.com/images/I/71Ru8tJ8lyL._AC_SL1500_.jpg',
      price: 89.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B3RYWXKF?tag=romkow-20',
      category: 'Kitchen',
    },
    {
      id: 'xmas-13',
      title: 'Silk Pillowcase Set',
      description: 'Luxurious mulberry silk pillowcases that reduce hair frizz and skin creases. Beauty sleep essential.',
      image: 'https://m.media-amazon.com/images/I/71yvUWGKjuL._AC_SL1500_.jpg',
      price: 54.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0851WDK5R?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'xmas-14',
      title: 'Vintage Pyrex Mixing Bowl Set',
      description: 'Collectible vintage-inspired Pyrex bowls in classic patterns. Perfect for baking enthusiasts.',
      image: 'https://m.media-amazon.com/images/I/81kBPdJLYKL._AC_SL1500_.jpg',
      price: 64.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B08ZJ6XFZV?tag=romkow-20',
      category: 'Kitchen',
    },
    {
      id: 'xmas-15',
      title: 'Ninja CREAMi Ice Cream Maker',
      description: 'Make custom ice cream, gelato, and sorbet at home. Perfect for health-conscious dessert lovers.',
      image: 'https://m.media-amazon.com/images/I/71YE1KZ0JRL._AC_SL1500_.jpg',
      price: 199.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B7CRSH7C?tag=romkow-20',
      category: 'Kitchen',
    },
    {
      id: 'xmas-16',
      title: 'Calpak Luka Duffel Bag',
      description: 'Stylish weekender bag with shoe compartment. Perfect for weekend getaways and gym trips.',
      image: 'https://m.media-amazon.com/images/I/81M5tJ6e02L._AC_SL1500_.jpg',
      price: 165.00,
      currency: 'USD',
      url: 'https://www.calpaktravel.com/products/luka-duffel',
      category: 'Travel',
    },
    {
      id: 'xmas-17',
      title: 'Shark Beauty FlexFusion Hair Dryer',
      description: 'Award-winning hair dryer with multiple attachments for salon-quality styling at home.',
      image: 'https://m.media-amazon.com/images/I/61wQpg3VfcL._AC_SL1500_.jpg',
      price: 299.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CXW6YV18?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'xmas-18',
      title: 'Cozy Earth Bamboo Sheet Set',
      description: 'Luxury bamboo sheets that regulate temperature and feel incredibly soft. Perfect for better sleep.',
      image: 'https://m.media-amazon.com/images/I/71h0a1SrUOL._AC_SL1500_.jpg',
      price: 359.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B5JCGQJP?tag=romkow-20',
      category: 'Home',
    },
    {
      id: 'xmas-19',
      title: 'Hydro Flask Wide Mouth with Flex Sip Lid',
      description: 'Insulated water bottle that keeps drinks at perfect temperature. Available in beautiful colors.',
      image: 'https://m.media-amazon.com/images/I/61rM4FPP+9L._AC_SL1500_.jpg',
      price: 44.95,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CW9NLLRP?tag=romkow-20',
      category: 'Lifestyle',
    },
    {
      id: 'xmas-20',
      title: 'Kindle Paperwhite Signature Edition',
      description: 'Premium e-reader with adjustable warm light, wireless charging, and 32GB storage. Perfect for bookworms.',
      image: 'https://m.media-amazon.com/images/I/51QCk82iGUL._AC_SL1000_.jpg',
      price: 189.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B08N3J8GTX?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'xmas-21',
      title: 'Diptyque Baies Candle',
      description: 'Luxury French candle with iconic berry scent. The ultimate in sophisticated home fragrance.',
      image: 'https://m.media-amazon.com/images/I/71TJ2F5OKHL._AC_SL1500_.jpg',
      price: 74.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B000C1UZ0M?tag=romkow-20',
      category: 'Home',
    },
    {
      id: 'xmas-22',
      title: 'Alo Yoga High-Waist Airlift Leggings',
      description: 'Buttery-soft performance leggings with 4-way stretch. Perfect for yoga and everyday wear.',
      image: 'https://m.media-amazon.com/images/I/51V5DMYM+QL._AC_SL1500_.jpg',
      price: 118.00,
      currency: 'USD',
      url: 'https://www.aloyoga.com/products/w5477r-high-waist-airlift-legging',
      category: 'Fashion',
    },
    {
      id: 'xmas-23',
      title: 'Revlon One-Step Volumizer Hair Dryer',
      description: 'Viral hair tool that dries and styles simultaneously. Salon blowout at home in minutes.',
      image: 'https://m.media-amazon.com/images/I/61Qnqy1cXZL._AC_SL1500_.jpg',
      price: 59.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B01LSUQSB0?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'xmas-24',
      title: 'Weighted Blanket 15 lbs',
      description: 'Therapeutic weighted blanket that promotes better sleep and reduces anxiety. Machine washable.',
      image: 'https://m.media-amazon.com/images/I/81oZ+PqLOSL._AC_SL1500_.jpg',
      price: 69.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07T6T7Q9H?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'xmas-25',
      title: 'Glossier Skincare Set',
      description: 'Curated set of cult-favorite skincare products including Milky Jelly cleanser and moisturizer.',
      image: 'https://m.media-amazon.com/images/I/61vwR7wW9WL._AC_SL1500_.jpg',
      price: 85.00,
      currency: 'USD',
      url: 'https://www.glossier.com/products/the-skincare-set',
      category: 'Beauty',
    },
  ],

  'stocking-stuffers-under-50-2025': [
    {
      id: 'stock-1',
      title: 'Apple AirTag 4 Pack',
      description: 'Never lose your keys, wallet, or luggage again. Precision tracking with Find My network.',
      image: 'https://m.media-amazon.com/images/I/71FH+1gOBDL._AC_SL1500_.jpg',
      price: 99.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0D54JW6VF?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'stock-2',
      title: 'Supergoop! Unseen Sunscreen SPF 40',
      description: 'Invisible, weightless facial sunscreen that doubles as makeup primer. Blue light protection included.',
      image: 'https://m.media-amazon.com/images/I/61CJU9YqsJL._AC_SL1500_.jpg',
      price: 38.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CGQFM7BT?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'stock-3',
      title: 'Rechargeable LED Beanie Hat',
      description: 'Reversible knit beanie with rechargeable LED light. Perfect for night walks and outdoor activities.',
      image: 'https://m.media-amazon.com/images/I/71EYN0MDZLL._AC_SL1500_.jpg',
      price: 24.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BHVCW1V9?tag=romkow-20',
      category: 'Accessories',
    },
    {
      id: 'stock-4',
      title: 'Cooling Eye Mask Gel',
      description: 'Reusable cooling gel eye mask that soothes puffy under-eyes and tired eyes. Spa treatment at home.',
      image: 'https://m.media-amazon.com/images/I/71M2TkiHgJL._AC_SL1500_.jpg',
      price: 14.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B7VNF6TV?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'stock-5',
      title: 'Felted Wool Initial Sweater Ornament',
      description: 'Handcrafted miniature sweater ornament with personalized initial. Cozy and meaningful holiday décor.',
      image: 'https://m.media-amazon.com/images/I/71kBaZZ+VqL._AC_SL1500_.jpg',
      price: 18.00,
      currency: 'USD',
      url: 'https://www.uncommongoods.com/product/initial-sweater-ornament',
      category: 'Decor',
    },
    {
      id: 'stock-6',
      title: 'Fruit AirTag Holder Charms',
      description: 'Adorable fruit-shaped silicone holders for AirTags. Attach to luggage, bags, or water bottles.',
      image: 'https://m.media-amazon.com/images/I/71ZCv7q7P4L._AC_SL1500_.jpg',
      price: 12.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0C13G6KH4?tag=romkow-20',
      category: 'Accessories',
    },
    {
      id: 'stock-7',
      title: 'Mini Coloring Books Set of 2',
      description: 'Pocket-sized coloring books for stress relief. Quick designs that take just minutes to complete.',
      image: 'https://m.media-amazon.com/images/I/81kGdP5hXVL._AC_SL1500_.jpg',
      price: 9.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BFY6J5P2?tag=romkow-20',
      category: 'Hobbies',
    },
    {
      id: 'stock-8',
      title: 'PopSockets Phone Grip and Stand',
      description: 'Collapsible grip and stand for phones. Makes holding and using your phone easier.',
      image: 'https://m.media-amazon.com/images/I/61WF6wUhI5L._AC_SL1500_.jpg',
      price: 14.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CW26W7ZD?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'stock-9',
      title: 'Lip Balm Gift Set - 6 Pack',
      description: 'Collection of nourishing lip balms in different flavors. Keep lips soft all winter long.',
      image: 'https://m.media-amazon.com/images/I/81M8QqbQmCL._AC_SL1500_.jpg',
      price: 19.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B2R3X1QG?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'stock-10',
      title: 'Cozy Fuzzy Socks 4-Pack',
      description: 'Ultra-soft fuzzy socks in fun patterns. Perfect for keeping toes warm all winter.',
      image: 'https://m.media-amazon.com/images/I/81ZV7J7fwSL._AC_SL1500_.jpg',
      price: 16.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BNVS4RT6?tag=romkow-20',
      category: 'Fashion',
    },
    {
      id: 'stock-11',
      title: 'Car Air Freshener Vent Clips',
      description: 'Set of 4 luxury car air fresheners with essential oil blends. Long-lasting fresh scent.',
      image: 'https://m.media-amazon.com/images/I/71M0rXJrOqL._AC_SL1500_.jpg',
      price: 22.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BZV3M4P6?tag=romkow-20',
      category: 'Auto',
    },
    {
      id: 'stock-12',
      title: 'Portable Phone Charger 10000mAh',
      description: 'Slim power bank that charges phones 2-3 times. Essential for travelers and busy days.',
      image: 'https://m.media-amazon.com/images/I/61aNb5MaWhL._AC_SL1500_.jpg',
      price: 29.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BW2W5TPP?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'stock-13',
      title: 'Gourmet Coffee Sampler Pack',
      description: 'Collection of single-serve specialty coffee pods in 12 different flavors. Coffee lover dream.',
      image: 'https://m.media-amazon.com/images/I/81TvQAGRsPL._AC_SL1500_.jpg',
      price: 34.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B7G1Y8ZP?tag=romkow-20',
      category: 'Food',
    },
    {
      id: 'stock-14',
      title: 'Leather Cord Organizer Roll',
      description: 'Compact cable organizer that keeps cords tangle-free. Perfect for tech accessories.',
      image: 'https://m.media-amazon.com/images/I/71Z9uXSfR5L._AC_SL1500_.jpg',
      price: 19.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BQHM9TG7?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'stock-15',
      title: 'Herb Growing Kit',
      description: 'Indoor herb garden starter kit with basil, mint, and parsley. Fresh herbs year-round.',
      image: 'https://m.media-amazon.com/images/I/81Y2z6cD2fL._AC_SL1500_.jpg',
      price: 27.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B08FCJVZ85?tag=romkow-20',
      category: 'Home',
    },
    {
      id: 'stock-16',
      title: 'Stainless Steel Reusable Straws Set',
      description: 'Eco-friendly metal straws with cleaning brush and carrying case. Reduce plastic waste.',
      image: 'https://m.media-amazon.com/images/I/71pW3s-XVTL._AC_SL1500_.jpg',
      price: 11.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07CKLP43H?tag=romkow-20',
      category: 'Eco',
    },
    {
      id: 'stock-17',
      title: 'Bath Bombs Gift Set',
      description: 'Luxurious bath bombs in 12 different scents. Transform any bath into a spa experience.',
      image: 'https://m.media-amazon.com/images/I/81nLU3qVTcL._AC_SL1500_.jpg',
      price: 24.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07DVLC4N8?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'stock-18',
      title: 'Portable Bluetooth Speaker',
      description: 'Waterproof mini speaker with surprisingly powerful sound. Perfect for shower or beach.',
      image: 'https://m.media-amazon.com/images/I/61j4vLdLgML._AC_SL1500_.jpg',
      price: 39.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B9ZXXPNJ?tag=romkow-20',
      category: 'Tech',
    },
    {
      id: 'stock-19',
      title: 'Japanese Fancy Erasers Set',
      description: 'Adorable collectible erasers shaped like sushi, desserts, and animals. Fun desk accessories.',
      image: 'https://m.media-amazon.com/images/I/81k8X9vH7tL._AC_SL1500_.jpg',
      price: 12.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BHKC1T5Y?tag=romkow-20',
      category: 'Stationery',
    },
    {
      id: 'stock-20',
      title: 'Moisturizing Gloves with Treatment',
      description: 'Spa gloves infused with shea butter for overnight hand treatment. Wake up to soft hands.',
      image: 'https://m.media-amazon.com/images/I/71T7XFpwjkL._AC_SL1500_.jpg',
      price: 14.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BLRB5MPV?tag=romkow-20',
      category: 'Beauty',
    },
    {
      id: 'stock-21',
      title: 'Mini Desktop Vacuum Cleaner',
      description: 'Rechargeable mini vacuum for keyboard, desk, and car. Keeps workspace tidy effortlessly.',
      image: 'https://m.media-amazon.com/images/I/61nFOHHyONL._AC_SL1500_.jpg',
      price: 16.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BN3DW7VP?tag=romkow-20',
      category: 'Office',
    },
    {
      id: 'stock-22',
      title: 'Scratch-Off World Map Poster',
      description: 'Track your travels by scratching off countries visited. Beautiful wall art for adventurers.',
      image: 'https://m.media-amazon.com/images/I/91WpP4vgdPL._AC_SL1500_.jpg',
      price: 19.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B077V8F6ZL?tag=romkow-20',
      category: 'Travel',
    },
    {
      id: 'stock-23',
      title: 'Playing Cards Deck - Luxury Design',
      description: 'Premium playing cards with stunning metallic design. Perfect for game nights.',
      image: 'https://m.media-amazon.com/images/I/81IfLaM3PPL._AC_SL1500_.jpg',
      price: 14.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B7PQKY7Y?tag=romkow-20',
      category: 'Games',
    },
    {
      id: 'stock-24',
      title: 'Silicone Ice Cube Trays with Lids',
      description: 'Set of 2 stackable ice trays that make perfectly shaped cubes. No spills, easy release.',
      image: 'https://m.media-amazon.com/images/I/71vJfMO3KBL._AC_SL1500_.jpg',
      price: 13.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BHK4SQ7X?tag=romkow-20',
      category: 'Kitchen',
    },
    {
      id: 'stock-25',
      title: 'Succulent Planter Set of 3',
      description: 'Cute ceramic planters with drainage holes. Perfect for small succulents and cacti.',
      image: 'https://m.media-amazon.com/images/I/71oWQZV3rNL._AC_SL1500_.jpg',
      price: 21.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B07FK1GGFT?tag=romkow-20',
      category: 'Home',
    },
  ],

  'anniversary-gifts-for-her-2025': [
    {
      id: 'anniv-1',
      title: 'Personalized Star Map Custom Print',
      description: 'Custom star constellation map showing the night sky on your special date. Romantic and meaningful.',
      image: 'https://m.media-amazon.com/images/I/81gX0Y3F4HL._AC_SL1500_.jpg',
      price: 49.99,
      currency: 'USD',
      url: 'https://www.uncommongoods.com/product/custom-star-map',
      category: 'Personalized',
    },
    {
      id: 'anniv-2',
      title: 'Custom Double Initial Ring',
      description: 'Delicate 18K gold-plated ring featuring both of your initials with CZ crystals. Elegant and personal.',
      image: 'https://m.media-amazon.com/images/I/71M6tqD-9yL._AC_SL1500_.jpg',
      price: 58.00,
      currency: 'USD',
      url: 'https://www.baublebar.com/product/custom-double-initial-ring',
      category: 'Jewelry',
    },
    {
      id: 'anniv-3',
      title: 'Light of Our Love Song Plaque',
      description: 'LED-backlit acrylic plaque with your photo and custom song. Unique animated effect when lit.',
      image: 'https://m.media-amazon.com/images/I/71kXvGhMKUL._AC_SL1500_.jpg',
      price: 89.99,
      currency: 'USD',
      url: 'https://www.groovygirlgifts.com/light-of-our-love-song-plaque',
      category: 'Personalized',
    },
    {
      id: 'anniv-4',
      title: 'Birthstone Necklace Gold',
      description: 'Dainty gold necklace featuring her birthstone. Timeless piece she can wear every day.',
      image: 'https://m.media-amazon.com/images/I/61ckFzLOASL._AC_SL1500_.jpg',
      price: 78.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BFR4SQJM?tag=romkow-20',
      category: 'Jewelry',
    },
    {
      id: 'anniv-5',
      title: 'Wonderbox Weekend Getaway for 2',
      description: 'Gift box with access to over 52,000 hotels worldwide. Choose your romantic destination together.',
      image: 'https://m.media-amazon.com/images/I/81IfYL5RaZL._AC_SL1500_.jpg',
      price: 299.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B1YVHF2C?tag=romkow-20',
      category: 'Experience',
    },
    {
      id: 'anniv-6',
      title: 'Engraved Leather Journal',
      description: 'Premium leather-bound journal with custom engraved message. Perfect for memories and dreams.',
      image: 'https://m.media-amazon.com/images/I/81Hgd4M3PgL._AC_SL1500_.jpg',
      price: 45.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B9KPGTQ5?tag=romkow-20',
      category: 'Personalized',
    },
    {
      id: 'anniv-7',
      title: 'Rose Quartz Crystal Set',
      description: 'Love stone set including necklace, bracelet, and healing crystals. Symbolizes love and romance.',
      image: 'https://m.media-amazon.com/images/I/71LjMJ8rKtL._AC_SL1500_.jpg',
      price: 39.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B08RNDQ1SM?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'anniv-8',
      title: 'Tiffany & Co. Return to Tiffany Heart Tag Bracelet',
      description: 'Iconic silver bracelet with heart tag charm. Classic Tiffany design that never goes out of style.',
      image: 'https://m.media-amazon.com/images/I/61nPk2R+lLL._AC_SL1500_.jpg',
      price: 325.00,
      currency: 'USD',
      url: 'https://www.tiffany.com/jewelry/bracelets/return-to-tiffany-heart-tag-bracelet/',
      category: 'Jewelry',
    },
    {
      id: 'anniv-9',
      title: 'Custom Couple Portrait Illustration',
      description: 'Hand-drawn digital portrait of you both in artistic style. Unique keepsake to treasure forever.',
      image: 'https://m.media-amazon.com/images/I/71jXN3tRZdL._AC_SL1500_.jpg',
      price: 65.00,
      currency: 'USD',
      url: 'https://www.etsy.com/listing/custom-couple-portrait',
      category: 'Art',
    },
    {
      id: 'anniv-10',
      title: 'Luxury Spa Gift Basket',
      description: 'Curated spa set with bath salts, body butter, candles, and silk eye mask. Relaxation at home.',
      image: 'https://m.media-amazon.com/images/I/91KlF+0wWYL._AC_SL1500_.jpg',
      price: 89.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B35ZRGQG?tag=romkow-20',
      category: 'Wellness',
    },
    {
      id: 'anniv-11',
      title: 'Personalized Coordinates Bracelet',
      description: 'Delicate bracelet engraved with coordinates of where you met or got engaged. Sentimental jewelry.',
      image: 'https://m.media-amazon.com/images/I/61P0gRzqVsL._AC_SL1500_.jpg',
      price: 54.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B7M9TKGP?tag=romkow-20',
      category: 'Jewelry',
    },
    {
      id: 'anniv-12',
      title: 'Book of Love Letters Kit',
      description: 'Beautiful boxed set for writing and collecting love letters. Create a romantic tradition together.',
      image: 'https://m.media-amazon.com/images/I/81zQNlY3OtL._AC_SL1500_.jpg',
      price: 32.00,
      currency: 'USD',
      url: 'https://www.uncommongoods.com/product/book-of-love-letters',
      category: 'Romantic',
    },
    {
      id: 'anniv-13',
      title: 'Champagne Gift Set with Flutes',
      description: 'Premium champagne paired with elegant crystal flutes. Toast to your love in style.',
      image: 'https://m.media-amazon.com/images/I/71vY4wFbG0L._AC_SL1500_.jpg',
      price: 125.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B8QMW12X?tag=romkow-20',
      category: 'Food & Drink',
    },
    {
      id: 'anniv-14',
      title: 'Pandora Moments Heart Clasp Charm Bracelet',
      description: 'Classic charm bracelet to commemorate special moments. Add charms over the years together.',
      image: 'https://m.media-amazon.com/images/I/61j2QKG5VIL._AC_SL1500_.jpg',
      price: 99.00,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0B5W9X4TF?tag=romkow-20',
      category: 'Jewelry',
    },
    {
      id: 'anniv-15',
      title: 'Custom Song Lyrics Print',
      description: 'Beautiful art print featuring lyrics from your special song. Personalized with your names and date.',
      image: 'https://m.media-amazon.com/images/I/71nM5y-krsL._AC_SL1500_.jpg',
      price: 42.00,
      currency: 'USD',
      url: 'https://www.etsy.com/listing/custom-song-lyrics-print',
      category: 'Art',
    },
  ],

  'thanksgiving-kitchen-gadgets-2025': [
    {
      id: 'thanks-1',
      title: 'Ninja Double Oven with Smart Cook',
      description: 'Revolutionary double oven that cooks two dishes simultaneously with separate settings. 12 cooking functions.',
      image: 'https://m.media-amazon.com/images/I/81IWZ2xNF7L._AC_SL1500_.jpg',
      price: 299.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0CLVP4XBG?tag=romkow-20',
      category: 'Appliances',
    },
    {
      id: 'thanks-2',
      title: 'ThermoPro Digital Meat Thermometer',
      description: 'Instant-read thermometer with 4-second response time. Ensure perfectly cooked turkey every time.',
      image: 'https://m.media-amazon.com/images/I/71w6N4YwU2L._AC_SL1500_.jpg',
      price: 79.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B09YZ1CN7K?tag=romkow-20',
      category: 'Tools',
    },
    {
      id: 'thanks-3',
      title: 'KitchenAid Artisan Stand Mixer',
      description: 'Iconic stand mixer in 45+ colors. Essential for holiday baking with 10-speed control.',
      image: 'https://m.media-amazon.com/images/I/81FDXdXe0BL._AC_SL1500_.jpg',
      price: 449.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0BXBL6XHT?tag=romkow-20',
      category: 'Appliances',
    },
    {
      id: 'thanks-4',
      title: 'Williams Sonoma Fat Separator',
      description: 'Premium gravy separator with strainer and stopper. Makes perfect lump-free gravy effortlessly.',
      image: 'https://m.media-amazon.com/images/I/71QKdXLnqGL._AC_SL1500_.jpg',
      price: 39.95,
      currency: 'USD',
      url: 'https://www.williams-sonoma.com/products/fat-separator/',
      category: 'Tools',
    },
    {
      id: 'thanks-5',
      title: 'Braun MultiQuick Hand Blender',
      description: 'Powerful immersion blender for soups and sides. Quiet operation with easy cleanup.',
      image: 'https://m.media-amazon.com/images/I/61rJ+jqEujL._AC_SL1500_.jpg',
      price: 69.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B00ARQVM5O?tag=romkow-20',
      category: 'Appliances',
    },
    {
      id: 'thanks-6',
      title: 'Etekcity Digital Kitchen Scale',
      description: 'Precision scale for perfect Thanksgiving baking. Multiple units (g, oz, lb, ml) with tare function.',
      image: 'https://m.media-amazon.com/images/I/71sNHbC6I5L._AC_SL1500_.jpg',
      price: 24.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0113UZJE2?tag=romkow-20',
      category: 'Tools',
    },
    {
      id: 'thanks-7',
      title: 'Ninja 10-in-1 PossibleCooker Pro',
      description: 'Multi-functional cooker with precise temperature control. Slow cook, braise, sear, and more.',
      image: 'https://m.media-amazon.com/images/I/81SqGvwkWIL._AC_SL1500_.jpg',
      price: 199.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B0C5T9WG4P?tag=romkow-20',
      category: 'Appliances',
    },
    {
      id: 'thanks-8',
      title: 'OXO Good Grips Roasting Pan',
      description: 'Non-stick roasting pan with removable rack. Perfect for turkey and large roasts.',
      image: 'https://m.media-amazon.com/images/I/81SfjWOWBdL._AC_SL1500_.jpg',
      price: 89.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B00IKLS5FY?tag=romkow-20',
      category: 'Cookware',
    },
    {
      id: 'thanks-9',
      title: 'Progressive Turkey Timer',
      description: 'Pop-up timer set that ensures perfectly cooked poultry. Essential Thanksgiving tool.',
      image: 'https://m.media-amazon.com/images/I/71aS5M+OTML._AC_SL1500_.jpg',
      price: 12.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B00004UE7V?tag=romkow-20',
      category: 'Tools',
    },
    {
      id: 'thanks-10',
      title: 'Cuisinart Food Processor 14-Cup',
      description: 'Large capacity food processor for chopping, slicing, and shredding. Thanksgiving prep made easy.',
      image: 'https://m.media-amazon.com/images/I/81Cn8FNxEuL._AC_SL1500_.jpg',
      price: 179.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B01AXM4WV2?tag=romkow-20',
      category: 'Appliances',
    },
    {
      id: 'thanks-11',
      title: 'Lodge Cast Iron Dutch Oven 7-Quart',
      description: 'Heavy-duty enameled cast iron for perfect side dishes and casseroles. Oven to table beauty.',
      image: 'https://m.media-amazon.com/images/I/81kdIWm04IL._AC_SL1500_.jpg',
      price: 89.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B000N501BK?tag=romkow-20',
      category: 'Cookware',
    },
    {
      id: 'thanks-12',
      title: 'Prepara Herb Saver Pod',
      description: 'Keep fresh herbs vibrant for weeks. Built-in water reservoir extends herb life dramatically.',
      image: 'https://m.media-amazon.com/images/I/61FVdoXrhTL._AC_SL1500_.jpg',
      price: 16.99,
      currency: 'USD',
      url: 'https://www.amazon.com/dp/B00NBDV3C6?tag=romkow-20',
      category: 'Storage',
    },
  ],
};
