export interface InspoItem {
  id: string;
  title: string;
  description: string;
  image: string;
  price: number;
  currency: string;
  url: string;
  category: string;
}

// Helper function to replace Amazon affiliate tags
function replaceAmazonAffiliate(url: string): string {
  if (!url.includes('amazon.com')) return url;

  // Remove existing affiliate tag if present
  const urlObj = new URL(url);
  urlObj.searchParams.delete('tag');

  // Add our affiliate tag
  urlObj.searchParams.set('tag', 'romkow-20');

  return urlObj.toString();
}

export const inspoItems: InspoItem[] = [
  {
    id: 'lulu-wunder-train',
    title: 'Wunder Train High-Rise Tight 28"',
    description: 'Breathable activewear with sweat-wicking technology',
    image: 'https://images.lululemon.com/is/image/lululemon/LW5DJ0S_0001_1',
    price: 98,
    currency: 'USD',
    url: 'https://shop.lululemon.com/p/womens-leggings/Wunder-Train-HR-Tight-28/?color=0001&sz=8',
    category: 'Fitness',
  },
  {
    id: 'lulu-define-jacket',
    title: 'Define Jacket *Nulu',
    description: 'Versatile fan-favorite jacket suitable for adventure and downtime',
    image: 'https://images.lululemon.com/is/image/lululemon/LW4CD5S_049106_1',
    price: 128,
    currency: 'USD',
    url: 'https://shop.lululemon.com/p/jackets-and-hoodies-jackets/Define-Jacket-Nulu/?color=71917',
    category: 'Fitness',
  },
  {
    id: 'lulu-swiftly-tech',
    title: 'Swiftly Tech Cropped Long-Sleeve Shirt 2.0',
    description: 'High-performing fabric designed for workouts and active use',
    image: 'https://images.lululemon.com/is/image/lululemon/LW3GH4S_0572_1',
    price: 78,
    currency: 'USD',
    url: 'https://shop.lululemon.com/p/tops-long-sleeve/Swiftly-Tech-Cropped-Long-Sleeve-Shirt-2/?color=71178&sz=0',
    category: 'Fitness',
  },
  {
    id: 'lulu-align-pants',
    title: 'lululemon Align No Line™ High-Rise Pant 25"',
    description: 'Lightweight, buttery soft yoga pants with seamless design',
    image: 'https://images.lululemon.com/is/image/lululemon/LW5IH1S_027216_1',
    price: 108,
    currency: 'USD',
    url: 'https://shop.lululemon.com/p/womens-leggings/lululemon-Align-No-Line-High-Rise-Pant-25/?color=30210&sz=8',
    category: 'Fitness',
  },
  {
    id: 'alo-tennis-skirt',
    title: 'Match Point Tennis Skirt',
    description: 'Stylish athletic tennis skirt for active lifestyle',
    image: 'https://cdn.shopify.com/s/files/1/2185/2813/files/W6240R_00_b2_s1_a1_m54.jpg?v=1761533639',
    price: 78,
    currency: 'USD',
    url: 'https://www.aloyoga.com/products/w6240r-match-point-tennis-skirt-white?variant=39398310805684',
    category: 'Fitness',
  },
  {
    id: 'ugg-tasman-slippers',
    title: "Women's Tasman II Slippers",
    description: 'Iconic slide with sheepskin interior and EVA comfort sole',
    image: 'https://dms.deckers.com/ugg/image/upload/t_product-xlarge-wp/v1741285643/1174470-BLK_1.png',
    price: 125,
    currency: 'USD',
    url: 'https://www.ugg.com/women-slippers/tasman-ii/1174470.html?dwvar_1174470_color=BLK',
    category: 'Footwear',
  },
  {
    id: 'digital-camera-kids',
    title: 'Digital Camera - FHD 1080P with 16X Zoom',
    description: 'Compact point-and-shoot camera perfect for kids and beginners',
    image: 'https://m.media-amazon.com/images/I/61JavBEclHL._SY500_.jpg',
    price: 39.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BTCZ2RR9'),
    category: 'Electronics',
  },
  {
    id: 'vtopmart-organizers',
    title: 'Vtopmart 25 PCS Drawer Organizers Set',
    description: 'Clear plastic storage trays with 4 sizes for bathroom and vanity',
    image: 'https://m.media-amazon.com/images/I/81yj+PUYVxL._SY500_.jpg',
    price: 16.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B08KXKVT4K'),
    category: 'Organization',
  },
  {
    id: 'eos-body-lotion',
    title: 'eos Shea Better Body Lotion - Vanilla Cashmere',
    description: 'Lightweight, non-greasy moisturizing lotion with natural shea butter',
    image: 'https://m.media-amazon.com/images/I/51lP01--ejL._SY500_.jpg',
    price: 8.74,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B08KT2Z93D'),
    category: 'Beauty',
  },
  {
    id: 'levoit-air-purifier',
    title: 'LEVOIT Air Purifiers Core Mini-P',
    description: '3-in-1 filter purifier for bedroom, office with aromatherapy',
    image: 'https://m.media-amazon.com/images/I/71wGv7Fh2AL._SY500_.jpg',
    price: 41.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B09GTRVJQM'),
    category: 'Home',
  },
  {
    id: 'vs-bare-vanilla',
    title: "Victoria's Secret Bare Vanilla Body Mist",
    description: 'Light fragrance spray with vanilla and cashmere notes',
    image: 'https://m.media-amazon.com/images/I/61cXiFL0BdL._SY500_.jpg',
    price: 16.94,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B07JRG42D9'),
    category: 'Beauty',
  },
  {
    id: 'hatch-restore',
    title: 'Hatch Restore 3 Sunrise Alarm Clock',
    description: 'Smart sleep device with sunrise simulation and white noise machine',
    image: 'https://m.media-amazon.com/images/I/81kueNVrxRL._SY500_.jpg',
    price: 168.12,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0DLLSCVZW'),
    category: 'Electronics',
  },
  {
    id: 'bedsure-throw-blanket',
    title: 'Bedsure GentleSoft White Throw Blanket 50x60"',
    description: 'Ultra-soft fleece throw blanket perfect for lounging or gifting',
    image: 'https://m.media-amazon.com/images/I/617jWhurG3L._SY500_.jpg',
    price: 12.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BPLB81LX'),
    category: 'Home',
  },
  {
    id: 'sacheu-lip-liner',
    title: 'Sacheu Lip Liner STAY-N Peel Off Lip Stain',
    description: 'Long-lasting matte lip stain with hyaluronic acid and vitamin E',
    image: 'https://m.media-amazon.com/images/I/51X-Nv2dlkL._SY500_.jpg',
    price: 14.00,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BVPNQW1C'),
    category: 'Beauty',
  },
  {
    id: 'nrizc-desk-chair',
    title: 'Nrizc Velvet Office Desk Chair',
    description: 'Ergonomic upholstered chair with adjustable swivel wheels',
    image: 'https://m.media-amazon.com/images/I/51ii8GOowVL._SY500_.jpg',
    price: 49.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B09XR1JD6F'),
    category: 'Furniture',
  },
  {
    id: 'airpods-4',
    title: 'Apple AirPods 4 Wireless Earbuds',
    description: 'Personalized spatial audio earbuds with water resistance',
    image: 'https://m.media-amazon.com/images/I/61iBtxCUabL._SY500_.jpg',
    price: 114.80,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0DGHMNQ5Z'),
    category: 'Electronics',
  },
  {
    id: 'bandaid-first-aid',
    title: 'BAND-AID Travel Ready First Aid Kit',
    description: 'Portable emergency first aid kit with 80 pieces for travel',
    image: 'https://m.media-amazon.com/images/I/81yqKXAIZhL._SY500_.jpg',
    price: 10.98,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0B41MYSGP'),
    category: 'Health',
  },
  {
    id: 'kodak-pixpro',
    title: 'KODAK PIXPRO Friendly Zoom FZ45 Digital Camera',
    description: '16MP digital camera with 4X optical zoom and wide angle lens',
    image: 'https://m.media-amazon.com/images/I/81gAqtMl3AL._SY500_.jpg',
    price: 119.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0B8PDHRWY'),
    category: 'Electronics',
  },
  {
    id: 'biodance-mask',
    title: 'BIODANCE Bio-Collagen Real Deep Mask',
    description: 'Hydrating overnight hydrogel mask for pore minimizing and elasticity',
    image: 'https://m.media-amazon.com/images/I/51Qiwz3ZiaL._SY500_.jpg',
    price: 16.90,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0B2RM68G2'),
    category: 'Beauty',
  },
  {
    id: 'fake-vines',
    title: '12 Pack Fake Vines Artificial Ivy Garland',
    description: 'Green artificial ivy with flowers for room and wall decoration',
    image: 'https://m.media-amazon.com/images/I/81FJ4m6f-XL._SY500_.jpg',
    price: 6.26,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B07JK99MB1'),
    category: 'Home Decor',
  },
  {
    id: 'medicube-mask',
    title: 'medicube Collagen Overnight Wrapping Peel Off Mask',
    description: 'Elasticity and hydration care Korean skincare mask pack',
    image: 'https://m.media-amazon.com/images/I/61occWCJN-L._SY500_.jpg',
    price: 19.00,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BRMYHMS5'),
    category: 'Beauty',
  },
  {
    id: 'cheirosa-39',
    title: 'Cheirosa 39 Hair & Body Perfume Mist',
    description: 'Luxurious fragrance mist for hair and body',
    image: 'https://media.ulta.com/i/ulta/2640715?w=500&h=500',
    price: 26.00,
    currency: 'USD',
    url: 'https://www.ulta.com/p/cheirosa-39-hair-body-perfume-mist-pimprod2052287',
    category: 'Beauty',
  },
  {
    id: 'beats-solo-4',
    title: 'Beats Solo 4 - Wireless Headphones',
    description: 'Bluetooth headphones with 50 hours battery life',
    image: 'https://m.media-amazon.com/images/I/51JNqP2C4rL._SY500_.jpg',
    price: 129.95,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0CZPGX972'),
    category: 'Electronics',
  },
  {
    id: 'command-strips',
    title: 'Command Variety Pack Picture Hanging Strips',
    description: 'Damage-free hanging system for pictures and décor',
    image: 'https://m.media-amazon.com/images/I/714tUfj1g-L._SY500_.jpg',
    price: 11.97,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B07712H557'),
    category: 'Home Decor',
  },
  {
    id: 'olaplex-7',
    title: 'Olaplex No. 7 Bonding Oil',
    description: 'Heat protectant oil for smooth, shiny, frizz-controlled hair',
    image: 'https://m.media-amazon.com/images/I/71ACqtMWo2L._SY500_.jpg',
    price: 30.00,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B07VR1NDSQ'),
    category: 'Beauty',
  },
  {
    id: 'skullpanda-box',
    title: 'POP MART SKULLPANDA Warmth Series Blind Box',
    description: 'Collectible toy figures with random design variations',
    image: 'https://m.media-amazon.com/images/I/61BMUm4Yy7L._SY500_.jpg',
    price: 19.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BG8QHZV5'),
    category: 'Toys',
  },
  {
    id: 'food-containers',
    title: 'Airtight Food Storage Containers - 24 Pack',
    description: 'BPA-free plastic canisters with labels for pantry organization',
    image: 'https://m.media-amazon.com/images/I/91ojIYPNCzL._SY500_.jpg',
    price: 29.44,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B08ZK5WDWN'),
    category: 'Kitchen',
  },
  {
    id: 'tree-hut-scrub',
    title: 'Tree Hut Shea Sugar Scrub',
    description: 'Exfoliating body scrub with nourishing shea butter',
    image: 'https://m.media-amazon.com/images/I/51sOmJOUlyL._SY500_.jpg',
    price: 8.94,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BX2TZZWG'),
    category: 'Beauty',
  },
  {
    id: 'sol-de-janeiro',
    title: 'SOL DE JANEIRO Hair & Body Perfume Mist',
    description: 'Tropical fragrance spray for hair and body',
    image: 'https://m.media-amazon.com/images/I/61iUgqAgoBL._SY500_.jpg',
    price: 38.00,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B09X3HB2BR'),
    category: 'Beauty',
  },
  {
    id: 'makeup-organizer',
    title: 'Rotating Makeup Organizer - 8 Adjustable Layers',
    description: 'Spinning cosmetic display carousel with brush holder and perfume tray',
    image: 'https://m.media-amazon.com/images/I/61cVCxMax5L._SY500_.jpg',
    price: 12.78,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BR9V9FKP'),
    category: 'Organization',
  },
  {
    id: 'baby-gift-set',
    title: 'MAMIMAKA Newborn Layette Gift Set - 24 Piece',
    description: 'Cotton bodysuits and pants essentials for newborns',
    image: 'https://m.media-amazon.com/images/I/71L-NJfRyTL._SY500_.jpg',
    price: 39.09,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B09R9LDTTJ'),
    category: 'Baby',
  },
  {
    id: 'ipad-11',
    title: 'Apple iPad 11-inch - A16 chip - 128GB',
    description: 'Latest iPad with liquid retina display and all-day battery',
    image: 'https://m.media-amazon.com/images/I/61F0JkimwfL._SY500_.jpg',
    price: 299.00,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0DZ7871B8'),
    category: 'Electronics',
  },
  {
    id: 'kitsch-spray-bottle',
    title: 'Kitsch Continuous Spray Bottle for Hair',
    description: 'Fine mist water bottle made from recycled materials',
    image: 'https://m.media-amazon.com/images/I/51u3yqZIjWL._SY500_.jpg',
    price: 7.19,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0CVZWMD34'),
    category: 'Beauty',
  },
  {
    id: 'shark-flexstyle',
    title: 'Shark HD430 FlexStyle Air Styling & Drying System',
    description: 'Multi-styler hair dryer with auto-wrap curlers and attachments',
    image: 'https://m.media-amazon.com/images/I/71XnLIh6Q1L._SY500_.jpg',
    price: 229.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0B89P16MC'),
    category: 'Beauty',
  },
  {
    id: 'lattafa-eclaire',
    title: 'Lattafa Eclaire Eau de Parfum',
    description: 'Long-lasting fragrance with vanilla, caramel, and floral notes',
    image: 'https://m.media-amazon.com/images/I/51nyrqSOiRL._SY500_.jpg',
    price: 28.05,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0D3J4BT2L'),
    category: 'Beauty',
  },
  {
    id: 'gold-bracelets',
    title: 'DEARMAY Gold Bracelets Set - Waterproof',
    description: '14K gold-plated jewelry set with dainty stackable bracelets',
    image: 'https://m.media-amazon.com/images/I/81gkX3N963L._SY500_.jpg',
    price: 14.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0C2P72WY6'),
    category: 'Jewelry',
  },
  {
    id: 'ugg-ultra-mini',
    title: "UGG® Women's Classic Ultra Mini Boots",
    description: 'Classic sheepskin boots in fresh moss green color',
    image: 'https://dms.deckers.com/ugg/image/upload/f_auto/q_auto/dpr_auto/b_rgb:f3f3f3/w_800/v1749764868/1116109-MMP_1.png',
    price: 125.00,
    currency: 'USD',
    url: 'https://www.ugg.com/women-boots-classic-boots/classic-ultra-mini/1116109.html',
    category: 'Footwear',
  },
  {
    id: 'handheld-steamer',
    title: 'OGHom Handheld Clothing Steamer',
    description: 'Portable 700W steam iron for garment care while traveling',
    image: 'https://m.media-amazon.com/images/I/51pG8jNdXGL._SY500_.jpg',
    price: 26.59,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0B9BKQ8S9'),
    category: 'Home',
  },
  {
    id: 'led-strip-lights',
    title: 'DAYBETTER LED Strip Lights 130ft',
    description: 'RGB color-changing decorative lights with remote control',
    image: 'https://m.media-amazon.com/images/I/81Pru4iSlsL._SY500_.jpg',
    price: 9.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0D4DJ6BRR'),
    category: 'Home Decor',
  },
  {
    id: 'jbl-clip-4',
    title: 'JBL Clip 4 - Portable Bluetooth Speaker',
    description: 'Compact waterproof speaker with carabiner and 10-hour playtime',
    image: 'https://m.media-amazon.com/images/I/71fokjPeLTL._SY500_.jpg',
    price: 64.95,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B08PJ4KQ1G'),
    category: 'Electronics',
  },
  {
    id: 'beetles-gel',
    title: 'Beetles Blooming Gel 15ml - Clear UV LED Gel Polish',
    description: 'Spreading effect gel with watercolor floral print capability',
    image: 'https://m.media-amazon.com/images/I/71qdwPz7DsL._SY500_.jpg',
    price: 7.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B09DKNYMD2'),
    category: 'Beauty',
  },
  {
    id: 'hoop-earrings',
    title: '6 Pairs 14K Gold Plated Hoop Earrings',
    description: 'Hypoallergenic chunky hoop earrings in varied twisted designs',
    image: 'https://m.media-amazon.com/images/I/71LMNHPa2NL._SY500_.jpg',
    price: 14.99,
    currency: 'USD',
    url: replaceAmazonAffiliate('https://amazon.com/dp/B0BW9235FT'),
    category: 'Jewelry',
  },
];

export const categories = Array.from(new Set(inspoItems.map((item) => item.category))).sort();
