name = "jinnie-web"
compatibility_date = "2024-10-21"
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility for server functions
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://openai-rewrite.onrender.com/jinnie/v1"
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyA4xvIGQ482y_bojE2aKzzQ7BsZCpGYEm8"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "wishlist-app-v2.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "wishlist-app-v2"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:100728931577:web:77333444301fa360fece28"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "wishlist-app-v2.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "100728931577"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-BRDJHGM96Y"
